sample/config/routes.rb
#!/config/routes.rb
=begin
Routing setup for the entire site.

@author Daryl Bennett
@author Taylor Wilson
=end

Rails.application.routes.draw do

  resources :songs do
    resources :comments
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  #reroute default page
  root 'pages#home'

  #map the url's to certain links (matched route)
  match '/home',     :to => 'pages#home',    via: [:get, :post]
  match '/song',     :to => 'songs#index',   via: [:get, :post]
  match '/contact',  :to => 'pages#contact', via: [:get, :post]
  match '/about',    :to => 'pages#about',   via: [:get, :post]
  match '/help',     :to => 'pages#help',    via: [:get, :post]
  match '/login',    :to => 'pages#login',   via: [:get, :post]
  match '/admin',    :to => 'pages#admin',   via: [:get, :post]
  match '/register', :to => 'users#new',     via: [:get, :post]

  #these are the default URL's
  #get 'pages/home'
  #get 'pages/contact'
  #get 'pages/about'
  #get 'pages/help'
  #get 'pages/login'
  #get 'pages/admin'
  #get 'pages/register'
end

sample/app/models/song.rb
class Song < ActiveRecord::Base
  has_many :comments
  validates :title,       presence: true
  validates :date,        presence: true
  validates :description, presence: true
  validates :lyrics,      presence: true

end

sample/app/controllers/songs_controller.rb
#!app/controller/songs_controller.rb
=begin
@author Taylor Wilson
@author Daryl Bennett

Controller for song objects. This controller is based on the controller 
created in the 'Getting Started' tutorial.
http://guides.rubyonrails.org/getting_started.html
=end

class SongsController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "admin", only: :destroy

  def index
    @songs = Song.all
    @title = "Forum"
  end

  def new
    @song  = Song.new
    @title = "Forum"
  end
 
  def create
    @song = Song.new(song_params)
 
    if @song.save
      redirect_to @song
    else
      render 'new'
    end
  end

  def show
    @song = Song.find(params[:id])
    @title = "Forum"
  end

  def edit
    @song = Song.find(params[:id])
    @title = "Forum"
  end

  def update
    @song = Song.find(params[:id])

    if @song.update(song_params)
      redirect_to @song
    else
      render 'edit'
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    redirect_to song_path
  end
 
  private
    def song_params
      params.require(:song).permit(:title, :date, :description, :link, :lyrics)
    end
end

sample/app/helpers/songs_helper.rb
module SongsHelper
end

sample/app/views/songs/_form.html.erb
<%= form_for :song, url: songs_path do |f| %>

  <% if @song.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@song.errors.count, "error") %> prohibited
      this song from being saved:</h2>
    <ul>
    <% @song.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row">
    <div class="large-12 columns">
      <label>Jam! Title
	<%= f.text_field :title, {:placeholder => "Enter the title of your Jam!" } %>
      </label>	
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <label>Date
        <%= f.text_field :date, {:placeholder => "Enter the date" } %>
      </label>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <label>Description
        <%= f.text_area :description, {:placeholder => "Enter a description of your Jam!" } %>
      </label>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <label>Link
        <%= f.text_field :link, {:placeholder => "Enter a URL" } %>
      </label>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <label>Lyrics
        <%= f.text_field :lyrics, {:placeholder => "Enter the lyrics" } %>
      </label>
    </div>
  </div>
    <%= f.submit "Save Jam!", {:class => "button expand" }  %>
<% end %>

sample/app/views/songs/edit.html.erb
<h1>Edit Jam</h1>
<img src="../../assets/banner.jpg" alt="a picture with musical symbols">
<%= render 'form' %>

sample/app/views/songs/index.html.erb
<h1>Welcome to the Jam! Forum</h1>
<p>
  <img src="../../assets/banner.jpg" alt="a picture with musical symbols">
</p>
<p>
  This forum is for you to use to share your Jams with the music community.
  We only ask that you share only your original work and respect
  the community. If you don't like someone's Jam post, keep it to yourself
  or kindly disappear.
</p>
<h2><small><%= link_to 'Share A New Jam!', new_song_path %></small></h2>

<table>
  <thead>
    <tr>
      <th>Jam! Title</th>
      <th>Date</th>
      <th>Description</th>
      <th>Link</th>
      <th>Lyrics</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <% @songs.each do |song| %>
    <tr>
      <td><%= song.title       %></td>
      <td><%= song.date        %></td>
      <td><%= song.description %></td>
      <td><%= song.link        %></td>
      <td><%= song.lyrics      %></td>
      <td><%= link_to 'Show',    song_path(song) %></td>
      <td><%= link_to 'Edit',    edit_song_path(song) %></td>
      <td><%= link_to 'Destroy', song_path(song),
              method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
   <% end %>
</table>

sample/app/views/songs/new.html.erb
<h1>Jam!</h1>
<p>
  <img src="../../assets/banner.jpg" alt="a picture with musical symbols">
</p>
<%= render 'form' %>

sample/app/views/songs/show.html.erb
<dl class="accordion" data-accordian>
  <dd>
    <h1><a href="#panel1">Jam! <%= @song.title %> </a></h1>
    <img src="../../assets/banner.jpg" alt="a picture with musical symbols">
    <div id="panel1" class="content active">
      <dl class="tabs" data-tab>
        <dd class="active"><a href="#panel2-1">Date</a></dd>
        <dd><a href="#panel2-2">Description</a></dd>
        <dd><a href="#panel2-3">Link</a></dd>
        <dd><a href="#panel2-4">Lyrics</a></dd>
      </dl>
      <div class="tabs-content">
        <div class="content active" id="panel2-1">
	  <p><%= @song.date %></p>
	</div>
        <div class="content active" id="panel2-2">
	  <p><%= @song.description %></p>
	</div>
        <div class="content active" id="panel2-3">
	  <p><%= @song.link %></p>
	</div>
        <div class="content active" id="panel2-4">
	  <p><%= @song.lyrics %></p>
	</div>
      </div>
   </dd>
  <dd>
</dl>
<br>
<p>
  <%= link_to 'Edit Jam!', edit_song_path(@song) %>
</p>
<hr>
<h1><small><a href="">Add A Comment</a></small></h1>
  <%= render "comments/form" %>
<hr>
<h1><small><a href="">Comments</a></small></h1>
  <%= render @song.comments %>